name: CI

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - run: mise run install

      - run: mise run codegen

      - name: Fail if changes on PR
        if: github.event_name == 'pull_request'
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "::error::Uncommitted changes detected. Please run 'mise run codegen' and 'mise run install' locally and commit the changes."
            git status
            git diff
            exit 1
          fi

      - name: Create PR for codegen changes
        if: github.event_name == 'push' && !startsWith(github.ref, 'refs/tags/')
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update generated code"
          title: "chore: update generated code"
          branch: "chore/codegen"
          base: ${{ github.ref_name }}

      - run: mise run ci

      - name: Release
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create ${{ github.ref_name }} --generate-notes

      - name: Upload Artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: README.md
